### PR TITLE
Space added in Formatting

### PR DESCRIPTION
**Pull request by cpowis15**
added a space in formatting

### CODE REVIEW

**Comment by matthewmccormick** [comment]
Good stuff 👍

**Review by iskrenkam — APPROVED** [review]
Nice space :)

**Review by 1bmfr3sh — APPROVED** [review]
looks good to moi

**Comment by MatthewJohn-Hall** [comment]
Seems fine.

**Review by AhmadRaza56 — APPROVED** [review]

**Review by anissanelson — APPROVED** [review]
:)

**Review by MatthewJohn-Hall — APPROVED** [review]
Seems reasonable

**Pull request merged**
